# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate total fuel required from a set of components via their masses.
#'
#' @param masses Masses of components
#' @return The total fuel required
#' @export
fuel_required <- function(masses) {
    .Call(`_aoc_fuel_required`, masses)
}

#' Recursively calculate the total fuel required to launch.
#'
#' This is if it takes x mass of fuel to launch then how much extra fuel
#' do we need to launch the addition x mass etc.
#'
#' @param mass The mass of the fuel to be launched
#' @return The total fuel required to launch
#' @export
fuel_recursive <- function(mass) {
    .Call(`_aoc_fuel_recursive`, mass)
}

#' Calculate total fuel required from a set of components via their masses.
#'
#' @param masses Masses of components
#' @return The total fuel required
#' @export
fuel_and_fuel_mass_required <- function(masses) {
    .Call(`_aoc_fuel_and_fuel_mass_required`, masses)
}

