# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate total fuel required from a set of components via their masses.
#'
#' @param masses Masses of components
#' @return The total fuel required
#' @export
fuel_required <- function(masses) {
    .Call(`_aoc_fuel_required`, masses)
}

#' Recursively calculate the total fuel required to launch.
#'
#' This is if it takes x mass of fuel to launch then how much extra fuel
#' do we need to launch the addition x mass etc.
#'
#' @param mass The mass of the fuel to be launched
#' @return The total fuel required to launch
#' @export
fuel_recursive <- function(mass) {
    .Call(`_aoc_fuel_recursive`, mass)
}

#' Calculate total fuel required from a set of components via their masses.
#'
#' @param masses Masses of components
#' @return The total fuel required
#' @export
fuel_and_fuel_mass_required <- function(masses) {
    .Call(`_aoc_fuel_and_fuel_mass_required`, masses)
}

#' Run intcode
#'
#' @param programme The intcode programme
#' @return The decoded intcode
#' @export
intcode <- function(programme) {
    .Call(`_aoc_intcode`, programme)
}

#' Problem asks us to run so arbitrary updates before decoding
#'
#' @param programme The intcode programme
#' @return The updated intcode
#' @export
update_programme <- function(programme) {
    .Call(`_aoc_update_programme`, programme)
}

#' Set noun and verb and run to get the output
#'
#' @param programme The number to get factors for
#' @export
set_input_and_run <- function(programme, noun, verb) {
    .Call(`_aoc_set_input_and_run`, programme, noun, verb)
}

#' Set noun and verb and run to get the output
#'
#' @param programme The number to get factors for
#' @export
get_19690720_input <- function(programme) {
    .Call(`_aoc_get_19690720_input`, programme)
}

